// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1716.robotCode2017fix.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1716.robotCode2017fix.Robot;

/**
 *
 */
public class TurnDegreesCommand extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	//Number of degrees to turn
	double degree;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public TurnDegreesCommand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.directionalSubsystem);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public TurnDegreesCommand(double turnDegree)
    {
    	degree = turnDegree;
    	requires(Robot.directionalSubsystem);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	//Set the pid setpoint, enable the directional subsystem, and resetting the gyro
    	Robot.directionalSubsystem.setSetpoint(degree);
    	Robot.directionalSubsystem.enable();
    	Robot.sensors.resetGyro();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//Nothing needs to be here since the pid system takes care of running the motor to reach the target degree
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	//Finished when the robot has turned the specified number of degrees
    	return Robot.directionalSubsystem.onTarget();
    }

    // Called once after isFinished returns true
    protected void end() {
    	//Disable the directional subsystem (bad things happen if this isn't done) and reset the gyros and encoders
    	Robot.directionalSubsystem.disable();
    	Robot.sensors.resetGyro();
    	Robot.sensors.resetEncoderLeft();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
