// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1716.robotCode2017fix.subsystems;

import org.usfirst.frc1716.robotCode2017fix.Robot;
import org.usfirst.frc1716.robotCode2017fix.RobotMap;
import org.usfirst.frc1716.robotCode2017fix.commands.*;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class driveTrain extends Subsystem {

	double driveOffset;
	double speed;
	double distance;
	double turnMag;
	double intake;
	double wound;
	double unWound;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController speedController1 = RobotMap.driveTrainSpeedController1;
    private final SpeedController speedController2 = RobotMap.driveTrainSpeedController2;
    private final SpeedController speedController3 = RobotMap.driveTrainSpeedController3;
    private final SpeedController speedController4 = RobotMap.driveTrainSpeedController4;
    private final RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new TeleOpCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void drive(double leftSpeed, double rightSpeed){
    	robotDrive41.tankDrive(leftSpeed, rightSpeed);
    }

    public void setOffset(double d){
    	driveOffset = d;
    }
    
    public double getOffset(){
    	return driveOffset;
    }
    
    public void setSpeed(double d){
    	speed = d;
    }
    
    public double getSpeed(){
    	return speed;
    }
    
    public void setDist(double d){
    	distance = d;
    }
    
    public double getDist(){
    	return distance;
    }
    
    public void setIntake(double d){
    	intake = d;
    }
    
    public double getIntake(){
    	return intake;
    }
    
   
    
    public void setMag(double d){
    	turnMag = d;
    }
    
    public double getMag(){
    	return turnMag;
    }
}

